In [44]:
pip install mysql.connector

Processing c:\users\sreya's pc\appdata\local\pip\cache\wheels\42\2f\c3\692fc7fc1f0d8c06b9175d94f0fc30f4f92348f5df5af1b8b7\mysql_connector-2.2.9-cp37-cp37m-win_amd64.whl
Note: you may need to restart the kernel to use updated packages.


In [45]:
pip install time

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time


In [1]:
import mysql.connector
from time import sleep

In [2]:
# CONNECTING TO THE AWS RDS DATABASE

connection = mysql.connector.connect(
    host = 'HOST-NAME',
    port = PORT-NUMBER,
    user = 'USER-NAME',
    password = 'PASSWORD',
    database= 'DATABASE-NAME'
    )

In [3]:
mycursor = connection.cursor()

### Creating Data

In [4]:
import numpy as np
from scipy.stats import truncnorm


In [5]:
# USING THIS FUNCTION TO CREATE NORMALLY DISTRIBUTED DATA
def get_truncated_normal(mean=0, sd=1, low=0, upp=10):
    return truncnorm(
        (low - mean) / sd, (upp - mean) / sd, loc=mean, scale=sd)

### Banbury

In [6]:
mycursor.execute("SHOW COLUMNS FROM scout.Banbury")
for x in mycursor:
    print(x)

('id', b'int unsigned', 'NO', bytearray(b'PRI'), None, 'auto_increment')
('DateInserted', b'datetime', 'NO', bytearray(b''), b'now()', 'DEFAULT_GENERATED')
('sheet_width', b'int', 'NO', bytearray(b''), None, '')


In [7]:
# DUMMY DATA 
banbury_width = get_truncated_normal(mean=20, sd=4, low=16, upp=26).rvs(200).astype(int)

In [8]:
banbury_width

array([21, 20, 18, 23, 22, 18, 23, 25, 23, 23, 20, 21, 19, 16, 22, 22, 25,
       19, 17, 17, 25, 16, 17, 21, 19, 18, 22, 21, 23, 17, 20, 23, 22, 23,
       20, 21, 16, 25, 21, 24, 16, 19, 19, 19, 18, 18, 20, 18, 19, 18, 18,
       21, 21, 20, 18, 19, 16, 23, 16, 18, 24, 23, 24, 22, 17, 19, 21, 22,
       18, 18, 23, 23, 24, 17, 22, 24, 16, 16, 19, 21, 21, 17, 18, 18, 17,
       19, 18, 19, 18, 17, 20, 16, 24, 24, 21, 22, 25, 21, 19, 24, 18, 17,
       22, 24, 17, 21, 23, 18, 17, 19, 22, 20, 20, 20, 17, 23, 20, 20, 21,
       23, 18, 16, 16, 21, 19, 20, 18, 24, 18, 20, 18, 19, 22, 19, 19, 21,
       24, 16, 25, 18, 23, 18, 20, 19, 20, 16, 25, 21, 21, 18, 18, 18, 18,
       19, 17, 18, 25, 24, 25, 22, 22, 16, 21, 21, 21, 20, 21, 23, 21, 18,
       16, 18, 18, 20, 18, 20, 25, 20, 20, 22, 20, 17, 23, 23, 25, 18, 16,
       19, 17, 18, 16, 16, 19, 16, 23, 21, 23, 19, 17, 20])

In [9]:
# UPDATING DATA OF BANBURY IN DATABASE WITH  GAP OF 10 SECS IN BETWEEN EVERY UPDATE
for i in banbury_width:
    sleep(10)
    sql = """INSERT INTO Banbury (`sheet_width`) VALUES (%s)"""
    val = (int(i),)
    mycursor.execute(sql,val)
    connection.commit()
    print('executed {}'.format(i))

executed 21
executed 20
executed 18
executed 23
executed 22
executed 18
executed 23
executed 25
executed 23
executed 23
executed 20
executed 21
executed 19
executed 16
executed 22
executed 22
executed 25
executed 19
executed 17
executed 17
executed 25
executed 16
executed 17
executed 21
executed 19
executed 18
executed 22
executed 21
executed 23
executed 17
executed 20
executed 23
executed 22
executed 23
executed 20
executed 21
executed 16
executed 25
executed 21
executed 24
executed 16
executed 19
executed 19
executed 19
executed 18
executed 18
executed 20
executed 18
executed 19
executed 18
executed 18
executed 21
executed 21
executed 20
executed 18
executed 19
executed 16
executed 23
executed 16
executed 18
executed 24
executed 23
executed 24
executed 22
executed 17
executed 19
executed 21
executed 22
executed 18
executed 18
executed 23
executed 23
executed 24
executed 17
executed 22
executed 24
executed 16
executed 16
executed 19
executed 21
executed 21
executed 17
executed 18
exec

In [57]:
mycursor.execute("SELECT * FROM Banbury")

In [58]:
myresult = mycursor.fetchall()

for x in myresult:
  print(x)

(1, datetime.datetime(2020, 11, 16, 12, 2, 21), 20)
(2, datetime.datetime(2020, 11, 16, 12, 2, 32), 18)
(3, datetime.datetime(2020, 11, 16, 12, 2, 42), 20)
(4, datetime.datetime(2020, 11, 16, 12, 2, 53), 21)
(5, datetime.datetime(2020, 11, 16, 12, 3, 3), 19)
(6, datetime.datetime(2020, 11, 16, 12, 3, 14), 21)
(7, datetime.datetime(2020, 11, 16, 12, 3, 25), 23)
(8, datetime.datetime(2020, 11, 16, 12, 3, 35), 19)
(9, datetime.datetime(2020, 11, 16, 12, 3, 46), 18)
(10, datetime.datetime(2020, 11, 16, 12, 3, 56), 25)
(11, datetime.datetime(2020, 11, 16, 12, 4, 7), 18)
(12, datetime.datetime(2020, 11, 16, 12, 4, 17), 22)
(13, datetime.datetime(2020, 11, 16, 12, 4, 28), 23)
(14, datetime.datetime(2020, 11, 16, 12, 4, 38), 18)
(15, datetime.datetime(2020, 11, 16, 12, 4, 49), 17)
(16, datetime.datetime(2020, 11, 16, 12, 4, 59), 26)
(17, datetime.datetime(2020, 11, 16, 12, 5, 10), 22)
(18, datetime.datetime(2020, 11, 16, 12, 5, 20), 18)
(19, datetime.datetime(2020, 11, 16, 12, 5, 31), 20)
(20,

### Fabric

In [10]:
fabric_temp = get_truncated_normal(mean=550, sd=50, low=475, upp=625).rvs(200).astype(int)
fabric_temp 

array([561, 544, 489, 518, 597, 521, 551, 499, 607, 579, 494, 488, 571,
       524, 564, 523, 541, 583, 555, 543, 600, 608, 514, 558, 573, 597,
       525, 534, 575, 565, 533, 584, 600, 531, 560, 490, 538, 536, 499,
       624, 521, 591, 554, 507, 544, 554, 532, 560, 553, 498, 553, 585,
       561, 546, 618, 564, 573, 567, 522, 616, 581, 562, 562, 520, 561,
       612, 547, 567, 540, 506, 493, 577, 516, 580, 540, 613, 536, 530,
       585, 508, 531, 580, 607, 570, 567, 566, 543, 578, 573, 556, 548,
       622, 543, 567, 544, 516, 517, 509, 569, 548, 611, 539, 598, 526,
       561, 543, 561, 534, 563, 490, 548, 614, 529, 602, 554, 526, 566,
       510, 484, 486, 489, 533, 576, 518, 581, 571, 592, 590, 596, 563,
       542, 551, 492, 558, 478, 510, 545, 530, 544, 594, 623, 558, 577,
       500, 489, 565, 477, 574, 587, 612, 561, 609, 544, 552, 593, 586,
       615, 531, 566, 576, 507, 574, 569, 497, 589, 479, 614, 506, 485,
       478, 579, 515, 579, 569, 597, 594, 565, 504, 546, 517, 55

In [22]:
fabric_width = get_truncated_normal(mean=1, sd=1, low=1.5, upp=3).rvs(200)
fabric_width

array([1.70837894, 2.03465681, 1.62642461, 2.55282877, 2.38852795,
       2.41503252, 2.69497582, 1.81726024, 1.59677516, 2.02493093,
       1.79015019, 2.30544117, 2.00616993, 2.00058969, 2.01164772,
       1.90586134, 2.30828529, 1.61614027, 1.83648809, 2.45369717,
       2.22813837, 1.96394343, 2.34795876, 2.48481834, 1.83151171,
       2.09767645, 2.1354571 , 2.45414497, 2.10086926, 2.01174801,
       1.73561234, 2.63526876, 1.6902001 , 1.8429383 , 2.62909019,
       2.25354583, 2.17423351, 1.87856977, 1.90179531, 2.74577474,
       1.62594618, 1.6789437 , 1.87855343, 2.33479789, 2.09703089,
       1.52996305, 1.54487031, 2.81573532, 1.95627631, 1.89519989,
       1.63104195, 2.42604658, 2.36689671, 2.67043782, 1.94083388,
       2.10721255, 1.62976579, 2.27205676, 2.28959501, 1.78684468,
       2.61068551, 1.53018208, 2.09683533, 2.01146236, 1.55629554,
       1.72262941, 2.44289402, 2.84992664, 1.62376571, 1.8533617 ,
       1.96465997, 1.72700879, 1.92836766, 2.43688026, 2.42070

In [12]:
for x,y in zip(fabric_width,fabric_temp):
    sleep(10)
    sql = """INSERT INTO Fabric (`sheet_width`,`temperature`) VALUES (%s,%s)"""
    val = (int(x),int(y),)
    mycursor.execute(sql,val)
    connection.commit()
    print('executed')

executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
executed
e

In [62]:
mycursor.execute("SELECT * FROM Fabric")

In [63]:
mycursor.fetchall()
for x in mycursor:
    print(x)

### winder

In [13]:
winder_temp = get_truncated_normal(mean=650, sd=50, low=575, upp=725).rvs(200).astype(int)
winder_temp

array([694, 669, 666, 684, 580, 647, 579, 627, 636, 678, 633, 621, 615,
       681, 614, 679, 653, 594, 662, 624, 608, 591, 688, 675, 602, 621,
       676, 647, 591, 707, 645, 683, 696, 607, 684, 626, 659, 591, 602,
       648, 706, 646, 615, 709, 666, 622, 650, 610, 589, 653, 637, 648,
       703, 656, 605, 674, 645, 605, 671, 658, 664, 661, 658, 583, 646,
       705, 690, 594, 657, 674, 633, 700, 650, 618, 720, 671, 626, 665,
       662, 622, 606, 616, 635, 626, 591, 619, 665, 619, 606, 675, 708,
       596, 682, 587, 595, 709, 711, 611, 712, 616, 672, 654, 674, 689,
       707, 642, 616, 700, 685, 671, 660, 624, 645, 637, 693, 584, 657,
       687, 698, 637, 649, 673, 584, 690, 671, 702, 673, 616, 709, 684,
       634, 708, 679, 694, 654, 593, 639, 583, 658, 623, 714, 581, 633,
       622, 689, 668, 666, 721, 612, 659, 673, 628, 653, 607, 621, 623,
       646, 628, 647, 618, 638, 657, 613, 673, 711, 660, 679, 657, 593,
       649, 685, 672, 658, 678, 699, 615, 648, 678, 691, 640, 67

In [14]:
for i in winder_temp:
    sleep(10)
    sql = """INSERT INTO winder (`temperature`) VALUES (%s)"""
    val = (int(i),)
    mycursor.execute(sql,val)
    connection.commit()
    print('executed {}'.format(i))

executed 694
executed 669
executed 666
executed 684
executed 580
executed 647
executed 579
executed 627
executed 636
executed 678
executed 633
executed 621
executed 615
executed 681
executed 614
executed 679
executed 653
executed 594
executed 662
executed 624
executed 608
executed 591
executed 688
executed 675
executed 602
executed 621
executed 676
executed 647
executed 591
executed 707
executed 645
executed 683
executed 696
executed 607
executed 684
executed 626
executed 659
executed 591
executed 602
executed 648
executed 706
executed 646
executed 615
executed 709
executed 666
executed 622
executed 650
executed 610
executed 589
executed 653
executed 637
executed 648
executed 703
executed 656
executed 605
executed 674
executed 645
executed 605
executed 671
executed 658
executed 664
executed 661
executed 658
executed 583
executed 646
executed 705
executed 690
executed 594
executed 657
executed 674
executed 633
executed 700
executed 650
executed 618
executed 720
executed 671
executed 626

### Cutter

In [15]:
cutter_width = get_truncated_normal(mean=9, sd=2, low=7, upp=11).rvs(200).astype(int)
cutter_width

array([ 8,  8,  8,  7,  8,  8,  8,  9,  7, 10,  8,  7,  8,  9,  8,  8,  9,
        9, 10,  7,  9,  9,  7,  7,  9, 10, 10,  7,  8,  9,  9,  9,  7, 10,
        9, 10,  9,  9,  8,  8,  9, 10, 10,  8,  7,  7,  9,  8,  7,  7,  7,
        8,  8,  9, 10,  8,  7, 10,  7,  8, 10, 10, 10,  7,  8,  8,  9,  8,
        9,  7,  9,  9,  9,  8,  7, 10,  7,  9, 10,  8,  7,  9,  8,  9,  8,
        8,  8,  9,  7,  7, 10,  9,  8,  9,  9,  9,  8,  9,  8, 10,  7, 10,
        9,  9, 10,  8,  9,  9,  8, 10,  9,  7,  8,  9, 10,  7,  7,  9,  9,
        7, 10,  8,  9,  8,  9, 10,  9,  7,  9,  9, 10,  8, 10,  9,  8,  7,
        9, 10,  8, 10,  8,  9,  9,  7,  9,  7,  9,  8, 10,  9,  8,  8, 10,
        9,  8,  8,  7,  9, 10,  8,  8,  9,  7, 10,  7,  9,  8,  9,  8,  8,
       10,  9,  9,  8,  7,  9,  7,  7, 10,  8,  9,  7,  7,  7,  7,  8,  7,
        7, 10,  8,  7,  9, 10,  9, 10,  8,  8,  8,  7, 10])

In [16]:
cutter_position_error = get_truncated_normal(mean=2, sd=1, low=0.5, upp=4).rvs(200).astype(int)
cutter_position_error

array([1, 2, 2, 1, 2, 1, 2, 1, 2, 3, 1, 1, 2, 1, 2, 2, 2, 3, 1, 2, 1, 1,
       1, 3, 2, 2, 2, 2, 1, 3, 2, 3, 2, 3, 3, 3, 2, 3, 2, 2, 2, 2, 3, 2,
       2, 0, 0, 2, 2, 2, 1, 1, 1, 1, 2, 1, 0, 0, 2, 2, 1, 1, 0, 0, 0, 0,
       3, 1, 2, 1, 1, 1, 0, 3, 3, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 2, 2, 3, 2, 0, 0, 1, 1, 1, 1, 1, 2, 2, 1, 0, 1, 1, 2, 2, 1, 3,
       2, 2, 1, 3, 3, 2, 2, 0, 1, 1, 0, 1, 1, 3, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 2, 1, 2, 3, 3, 2, 2, 1, 2, 0, 1, 2, 1, 2, 2, 2, 3, 1, 1, 2, 0,
       2, 2, 3, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 0, 0, 0, 3, 1, 2, 3,
       1, 2, 1, 1, 1, 2, 1, 2, 0, 3, 1, 1, 2, 2, 1, 2, 1, 0, 2, 2, 0, 0,
       1, 1])

In [17]:
cutter_speed_error = get_truncated_normal(mean=3, sd=1, low=1, upp=5).rvs(200).astype(int)
cutter_speed_error 

array([3, 3, 3, 2, 2, 1, 4, 3, 4, 2, 3, 2, 4, 2, 2, 3, 4, 3, 3, 3, 2, 3,
       2, 3, 2, 4, 4, 3, 3, 3, 1, 3, 2, 3, 2, 2, 2, 3, 3, 2, 3, 3, 3, 2,
       3, 3, 1, 1, 4, 4, 4, 3, 4, 1, 4, 3, 2, 2, 2, 2, 2, 3, 2, 1, 3, 3,
       2, 2, 1, 2, 2, 2, 4, 3, 3, 4, 4, 1, 4, 2, 3, 2, 1, 4, 3, 2, 1, 3,
       2, 3, 1, 1, 3, 4, 3, 1, 3, 2, 2, 3, 3, 2, 3, 3, 3, 2, 2, 4, 1, 3,
       2, 2, 2, 3, 3, 2, 4, 3, 3, 2, 2, 1, 2, 3, 3, 3, 4, 4, 3, 4, 2, 3,
       3, 1, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 1, 3, 4, 2, 2, 3, 3, 3, 2, 3,
       4, 1, 2, 3, 2, 4, 2, 2, 3, 2, 1, 3, 4, 1, 4, 3, 3, 3, 4, 3, 3, 2,
       3, 4, 1, 2, 3, 3, 4, 1, 3, 2, 4, 2, 2, 3, 3, 4, 4, 4, 3, 2, 1, 3,
       1, 4])

In [18]:
for x,y,z in zip(cutter_width,cutter_position_error,cutter_speed_error):
    sleep(10)
    sql = """INSERT INTO cutter (`thread_with`,`position_error`,`speed_error`) VALUES (%s,%s,%s)"""
    val = (int(x),int(y),int(z),)
    mycursor.execute(sql,val)
    connection.commit()
    print('executed {}'.format(i))

executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668

### curing

In [19]:
curing_temp = get_truncated_normal(mean=225, sd=25, low=175, upp=275).rvs(200).astype(int)
curing_temp

array([256, 221, 227, 269, 201, 244, 233, 217, 186, 190, 230, 252, 202,
       252, 227, 241, 216, 209, 205, 231, 186, 229, 265, 192, 243, 230,
       215, 243, 239, 230, 256, 269, 239, 212, 200, 242, 262, 234, 251,
       271, 202, 229, 234, 240, 233, 198, 230, 245, 222, 219, 200, 222,
       210, 245, 269, 233, 206, 258, 220, 205, 244, 224, 223, 238, 240,
       228, 233, 237, 251, 248, 240, 219, 236, 243, 220, 195, 238, 233,
       230, 247, 213, 239, 197, 246, 218, 231, 207, 181, 203, 210, 208,
       183, 253, 218, 249, 214, 182, 231, 194, 217, 242, 215, 232, 225,
       210, 207, 230, 238, 223, 247, 257, 197, 250, 208, 236, 238, 212,
       232, 211, 190, 234, 220, 200, 206, 219, 210, 223, 209, 243, 210,
       194, 232, 189, 219, 253, 194, 197, 181, 235, 196, 211, 241, 228,
       214, 241, 208, 263, 243, 182, 249, 245, 238, 199, 224, 214, 206,
       234, 212, 235, 207, 244, 210, 255, 252, 224, 249, 215, 248, 208,
       203, 178, 243, 252, 236, 230, 194, 194, 231, 213, 216, 26

In [20]:
curing_mold = get_truncated_normal(mean=35, sd=2, low=30, upp=45).rvs(200).astype(int)
curing_mold

array([39, 32, 31, 39, 34, 35, 37, 37, 35, 36, 34, 35, 38, 36, 38, 40, 33,
       36, 40, 39, 37, 36, 35, 38, 34, 35, 33, 34, 35, 37, 32, 34, 37, 36,
       39, 34, 32, 33, 33, 37, 35, 30, 36, 35, 36, 34, 38, 33, 36, 34, 33,
       37, 35, 34, 33, 31, 35, 34, 37, 36, 35, 34, 34, 34, 36, 37, 34, 33,
       35, 36, 33, 39, 33, 30, 34, 34, 36, 36, 34, 35, 35, 35, 33, 34, 32,
       33, 34, 35, 31, 36, 34, 36, 30, 35, 34, 33, 35, 37, 35, 35, 33, 35,
       35, 37, 34, 35, 35, 31, 32, 34, 39, 33, 33, 31, 32, 37, 33, 35, 36,
       35, 37, 35, 38, 37, 38, 34, 36, 35, 33, 34, 32, 33, 35, 33, 33, 35,
       32, 32, 35, 35, 38, 32, 34, 33, 35, 35, 32, 31, 34, 32, 31, 35, 32,
       35, 33, 36, 36, 34, 38, 36, 33, 37, 36, 34, 34, 38, 31, 34, 32, 34,
       36, 38, 38, 32, 34, 36, 37, 31, 37, 32, 34, 34, 34, 33, 33, 37, 34,
       38, 36, 33, 35, 33, 33, 35, 35, 37, 34, 31, 34, 34])

In [21]:
for x,y in zip(curing_temp,curing_mold):
    sleep(10)
    sql = """INSERT INTO curing (`temperature`,`molding_time_mins`) VALUES (%s,%s)"""
    val = (int(x),int(y),)
    mycursor.execute(sql,val)
    connection.commit()
    print('executed {}'.format(i))

executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668
executed 668